/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3cayonlineclient;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author HuyNguyen
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    Socket socket;
    ObjectInputStream input;
    ObjectOutputStream output;
    
    public MainFrame() {
        initComponents();
        try {
            this.socket = new Socket("localhost", 1352);

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Some = new javax.swing.JButton();
        other = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Some.setText("Some");
        Some.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomeActionPerformed(evt);
            }
        });

        other.setText("other");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(Some)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(other)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Some)
                    .addComponent(other))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomeActionPerformed

        
               
        
        new Thread(() -> {
            try {
            // TODO add your handling code here:
            
            
            if(this.output == null) {
                this.output = new ObjectOutputStream(socket.getOutputStream());
            }
            
            this.output.writeObject("someaction");
            
            if(this.input == null) {
                this.input = new ObjectInputStream(socket.getInputStream());
            }
            
            String res = (String) this.input.readObject();
            
            System.out.println(res);
                        
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }).start();
         
    }//GEN-LAST:event_SomeActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            try {
            // TODO add your handling code here:
            
            
            if(this.output == null) {
                this.output = new ObjectOutputStream(socket.getOutputStream());
            }
            
            this.output.writeObject("otheraction");
            
            if(this.input == null) {
                this.input = new ObjectInputStream(socket.getInputStream());
            }
            
            String res = (String) this.input.readObject();
            
            System.out.println(res);
            this.socket.close();
                        
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }).start();
    }//GEN-LAST:event_otherActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Some;
    private javax.swing.JButton other;
    // End of variables declaration//GEN-END:variables
}
